#!/bin/bash
# Generated by Session Manager — classify Bash commands
COMMAND=$(cat)
DECISION="ask"

jq -n --arg d "$DECISION" '{
  hookSpecificOutput: {
    hookEventName: "PreToolUse",
    permissionDecision: $d
  }
}'
