import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';

export type Profile = 'android' | 'frontend' | 'python' | 'generic';

// Дополнительный bash-whitelist для каждого профиля в формате case-строк
const PROFILE_WHITELIST: Record<Profile, string> = {
  android: `
    "gradlew"*|"./gradlew"*)
      DECISION="allow" ;;
    "adb"*)
      DECISION="allow" ;;`,
  frontend: `
    "npm"*|"npx"*|"yarn"*|"pnpm"*)
      DECISION="allow" ;;`,
  python: `
    "pip"*|"pytest"*|"poetry"*|"python"*|"python3"*)
      DECISION="allow" ;;`,
  generic: '',
};

function generateHookScript(profile: Profile): string {
  return `#!/bin/bash
# Generated by Session Manager — classify Bash commands
# Profile: ${profile}
COMMAND=$(cat)
DECISION="allow"

case "$COMMAND" in
  # --- Safe Git commands ---
  "git status"*|"git diff"*|"git log"*|"git commit"*|"git add"*|"git branch"*)
    DECISION="allow" ;;
  # --- Profile-specific ---${PROFILE_WHITELIST[profile]}
  # --- Explicitly dangerous ---
  "rm -rf"*|"git push --force"*|"git push -f"*|"curl"*"| bash"*|"curl"*"| sh"*)
    DECISION="deny" ;;
  # --- Everything else: allow (run without prompting) ---
  *)
    DECISION="allow" ;;
esac

jq -n --arg d "$DECISION" '{
  hookSpecificOutput: {
    hookEventName: "PreToolUse",
    permissionDecision: $d
  }
}'
`;
}

// Known MCP servers, used as a fallback when ~/.claude.json can't be read.
// Server names with ':' (e.g. 'generic:jira') are normalised to '_' in Claude
// Code permission rules, so the allow entry is 'mcp__generic_jira'.
const FALLBACK_MCP_SERVERS = [
  'generic_allure',
  'generic_apptracer',
  'generic_confluence',
  'generic_gitlab',
  'generic_jira',
  'vkws',
];

/**
 * Build permission rules that allow every MCP server's tools.
 *
 * Claude Code does NOT expand `mcp__*` (a `*` in the server position never
 * matches), so we must enumerate each server explicitly: `mcp__<server>` or
 * `mcp__<server>__*`. Servers are read from the global ~/.claude.json config.
 */
function getMcpAllowRules(): string[] {
  try {
    const claudeJson = JSON.parse(
      fs.readFileSync(path.join(os.homedir(), '.claude.json'), 'utf-8')
    );
    const servers = Object.keys(claudeJson.mcpServers ?? {});
    if (servers.length > 0) {
      return servers.map(s => `mcp__${s.replace(/[^a-zA-Z0-9_-]/g, '_')}`);
    }
  } catch {
    // fall through to static list
  }
  return FALLBACK_MCP_SERVERS.map(s => `mcp__${s}`);
}

const BACKUP_SUFFIX = '.backup';

function realpath(p: string): string {
  try {
    return fs.realpathSync(p);
  } catch {
    return path.resolve(p);
  }
}

/**
 * True for paths whose `.claude` directory is NOT project-local: $HOME (whose
 * .claude IS the global Claude Code config) and the filesystem root. Writing a
 * generated settings.json there would clobber the user's global configuration
 * and register project hooks with relative paths globally.
 */
export function isProtectedConfigPath(projectPath: string): boolean {
  const target = realpath(projectPath);
  return target === realpath(os.homedir()) || target === path.parse(target).root;
}

/**
 * Whether Claude Code trusts this workspace. Untrusted workspaces silently
 * ignore every permissions.allow entry from project settings files, so the
 * permissions we generate have no effect there.
 */
export function isWorkspaceTrusted(projectPath: string): boolean {
  try {
    const claudeJson = JSON.parse(
      fs.readFileSync(path.join(os.homedir(), '.claude.json'), 'utf-8')
    );
    const entry = (claudeJson.projects ?? {})[realpath(projectPath)]
      ?? (claudeJson.projects ?? {})[projectPath];
    return entry?.hasTrustDialogAccepted === true;
  } catch {
    return true; // can't tell — don't cry wolf
  }
}

/** Copy `file` to `file.backup` once, before we overwrite it for the first time. */
function backupOnce(file: string): void {
  const backup = file + BACKUP_SUFFIX;
  if (!fs.existsSync(file)) return;  // nothing to back up
  if (fs.existsSync(backup)) return; // already backed up
  fs.copyFileSync(file, backup);
}

function generateSettingsJson(): string {
  const settings = {
    permissions: {
      allow: [...getMcpAllowRules(), 'Read', 'Glob', 'Grep', 'Edit', 'Write'],
      deny: [
        'Read(.env*)',
        'Bash(rm -rf *)',
        'Bash(git push --force *)',
      ],
    },
    hooks: {
      PreToolUse: [
        {
          matcher: 'Bash',
          hooks: [
            {
              type: 'command',
              command: '.claude/hooks/classify-bash.sh',
            },
          ],
        },
      ],
    },
  };
  return JSON.stringify(settings, null, 2) + '\n';
}

function ensureGitignore(projectPath: string): void {
  const gitignorePath = path.join(projectPath, '.gitignore');
  const entry = '.claude/';

  let content = '';
  if (fs.existsSync(gitignorePath)) {
    content = fs.readFileSync(gitignorePath, 'utf-8');
  }

  // Check if .claude is already ignored
  const lines = content.split('\n');
  if (lines.some(l => l.trim() === '.claude/' || l.trim() === '.claude')) {
    return;
  }

  // Append with a newline separator if needed
  const toAppend = (content && !content.endsWith('\n') ? '\n' : '') + entry + '\n';
  fs.appendFileSync(gitignorePath, toAppend, 'utf-8');
}

export function sync(projectPath: string, profile: Profile): void {
  if (isProtectedConfigPath(projectPath)) {
    // Never generate project config into the global ~/.claude — doing so
    // replaces the user's own permissions and registers a PreToolUse hook
    // with a relative path that breaks in every other directory.
    console.warn(
      `Refusing to write Claude config into '${projectPath}': it is the global config location, not a project`
    );
    return;
  }

  const claudeDir = path.join(projectPath, '.claude');
  const hooksDir = path.join(claudeDir, 'hooks');
  const settingsFile = path.join(claudeDir, 'settings.json');
  const hookFile = path.join(hooksDir, 'classify-bash.sh');

  // Create directories first — ensures projectPath exists before writing files
  if (!fs.existsSync(claudeDir)) {
    fs.mkdirSync(claudeDir, { recursive: true });
  }
  if (!fs.existsSync(hooksDir)) {
    fs.mkdirSync(hooksDir, { recursive: true });
  }

  // Ensure .claude/ is gitignored after directories exist
  ensureGitignore(projectPath);

  // Always overwrite — but keep a one-time backup of whatever was there before
  backupOnce(settingsFile);
  fs.writeFileSync(settingsFile, generateSettingsJson(), 'utf-8');
  fs.writeFileSync(hookFile, generateHookScript(profile), 'utf-8');
  fs.chmodSync(hookFile, 0o755);
}

function generateLocalSettingsJson(): string {
  const settings = {
    permissions: {
      allow: [...getMcpAllowRules(), 'Read', 'Glob', 'Grep', 'Edit', 'Write', 'Bash'],
    },
    hooks: {
      PreToolUse: [
        {
          matcher: 'Bash',
          hooks: [
            {
              type: 'command',
              command: '.claude/hooks/classify-bash.sh',
            },
          ],
        },
      ],
    },
  };
  return JSON.stringify(settings, null, 2) + '\n';
}

// Runs currently holding a project's settings.local.json, keyed by project path.
// Holder ids (work ids) instead of a plain counter: a stray release for a work
// that never acquired can no longer restore the file under a live run, and a
// re-spawn of the same work is idempotent.
const localSettingsHolders = new Map<string, Set<string>>();

/** Whether any run currently holds this project's generated settings.local.json. */
export function hasActiveLocalSettings(projectPath: string): boolean {
  return (localSettingsHolders.get(projectPath)?.size ?? 0) > 0;
}

/**
 * Acquire local settings for a run. Backs up the user's original
 * settings.local.json (if present) on the first active run, then writes
 * our permissive settings. Safe to call concurrently — only the first
 * call creates a backup, only the last matching release() restores it.
 */
export function acquireLocalSettings(projectPath: string, holderId: string): void {
  let holders = localSettingsHolders.get(projectPath);
  if (!holders) {
    holders = new Set();
    localSettingsHolders.set(projectPath, holders);
  }
  if (holders.size === 0) {
    backupLocalSettings(projectPath);
  }
  holders.add(holderId);
  writeLocalSettings(projectPath);
}

/**
 * Release local settings after a run finishes. Restores the user's
 * original settings.local.json only when no other runs remain active
 * in the same project directory. A release from a holder that never
 * acquired is ignored — otherwise stopping or deleting an idle Work
 * would strip permissions from a sibling run that is still going.
 */
export function releaseLocalSettings(projectPath: string, holderId: string): void {
  const holders = localSettingsHolders.get(projectPath);
  if (!holders || !holders.delete(holderId)) {
    return; // this holder never acquired — nothing to release
  }
  if (holders.size === 0) {
    localSettingsHolders.delete(projectPath);
    restoreLocalSettings(projectPath);
  }
}

/**
 * Release all local settings — used on app shutdown to restore every
 * project's original settings.local.json regardless of active holders.
 */
export function releaseAllLocalSettings(): void {
  for (const [projectPath] of localSettingsHolders) {
    restoreLocalSettings(projectPath);
  }
  localSettingsHolders.clear();
}

/**
 * Restore user's settings.local.json from backup. Exported for crash
 * recovery (recoverStaleWorks) where in-memory counters are lost.
 */
export function restoreLocalSettings(projectPath: string): void {
  const localSettings = path.join(projectPath, '.claude', 'settings.local.json');
  const backupFile = localSettings + BACKUP_SUFFIX;

  if (fs.existsSync(backupFile)) {
    fs.copyFileSync(backupFile, localSettings);
    fs.unlinkSync(backupFile);
  }
  // No backup = user had no settings.local.json before the run.
  // Leave our file in place — it's harmless and ensures permissions until next sync.
}

// ---- Internal ----

function backupLocalSettings(projectPath: string): void {
  backupOnce(path.join(projectPath, '.claude', 'settings.local.json'));
}

function writeLocalSettings(projectPath: string): void {
  const claudeDir = path.join(projectPath, '.claude');
  if (!fs.existsSync(claudeDir)) {
    fs.mkdirSync(claudeDir, { recursive: true });
  }
  const localSettings = path.join(claudeDir, 'settings.local.json');
  fs.writeFileSync(localSettings, generateLocalSettingsJson(), 'utf-8');
}

export { generateHookScript };
