import * as fs from 'fs';
import * as path from 'path';

export type Profile = 'android' | 'frontend' | 'python' | 'generic';

// Дополнительный bash-whitelist для каждого профиля в формате case-строк
const PROFILE_WHITELIST: Record<Profile, string> = {
  android: `
    "gradlew"*|"./gradlew"*)
      DECISION="allow" ;;
    "adb"*)
      DECISION="allow" ;;`,
  frontend: `
    "npm"*|"npx"*|"yarn"*|"pnpm"*)
      DECISION="allow" ;;`,
  python: `
    "pip"*|"pytest"*|"poetry"*|"python"*|"python3"*)
      DECISION="allow" ;;`,
  generic: '',
};

function generateHookScript(profile: Profile): string {
  return `#!/bin/bash
# Generated by Session Manager — classify Bash commands
# Profile: ${profile}
COMMAND=$(cat)
DECISION="ask"

case "$COMMAND" in
  # --- Safe Git commands ---
  "git status"*|"git diff"*|"git log"*|"git commit"*|"git add"*|"git branch"*)
    DECISION="allow" ;;
  # --- Profile-specific ---${PROFILE_WHITELIST[profile]}
  # --- Explicitly dangerous ---
  "rm -rf"*|"git push --force"*|"git push -f"*|"curl"*"| bash"*|"curl"*"| sh"*)
    DECISION="deny" ;;
  # --- Everything else: ask ---
  *)
    DECISION="ask" ;;
esac

jq -n --arg d "$DECISION" '{
  hookSpecificOutput: {
    hookEventName: "PreToolUse",
    permissionDecision: $d
  }
}'
`;
}

function generateSettingsJson(): string {
  const settings = {
    permissions: {
      allow: ['Read', 'Glob', 'Grep', 'Edit', 'Write'],
      deny: [
        'Read(.env*)',
        'Bash(rm -rf *)',
        'Bash(git push --force *)',
      ],
    },
    hooks: {
      PreToolUse: [
        {
          matcher: 'Bash',
          hooks: [
            {
              type: 'command',
              command: '.claude/hooks/classify-bash.sh',
            },
          ],
        },
      ],
    },
  };
  return JSON.stringify(settings, null, 2) + '\n';
}

function ensureGitignore(projectPath: string): void {
  const gitignorePath = path.join(projectPath, '.gitignore');
  const entry = '.claude/';

  let content = '';
  if (fs.existsSync(gitignorePath)) {
    content = fs.readFileSync(gitignorePath, 'utf-8');
  }

  // Check if .claude is already ignored
  const lines = content.split('\n');
  if (lines.some(l => l.trim() === '.claude/' || l.trim() === '.claude')) {
    return;
  }

  // Append with a newline separator if needed
  const toAppend = (content && !content.endsWith('\n') ? '\n' : '') + entry + '\n';
  fs.appendFileSync(gitignorePath, toAppend, 'utf-8');
}

export function sync(projectPath: string, profile: Profile): void {
  const claudeDir = path.join(projectPath, '.claude');
  const hooksDir = path.join(claudeDir, 'hooks');
  const settingsFile = path.join(claudeDir, 'settings.json');
  const hookFile = path.join(hooksDir, 'classify-bash.sh');

  // Create directories first — ensures projectPath exists before writing files
  if (!fs.existsSync(claudeDir)) {
    fs.mkdirSync(claudeDir, { recursive: true });
  }
  if (!fs.existsSync(hooksDir)) {
    fs.mkdirSync(hooksDir, { recursive: true });
  }

  // Ensure .claude/ is gitignored after directories exist
  ensureGitignore(projectPath);

  // Always overwrite
  fs.writeFileSync(settingsFile, generateSettingsJson(), 'utf-8');
  fs.writeFileSync(hookFile, generateHookScript(profile), 'utf-8');
  fs.chmodSync(hookFile, 0o755);
}

function generateLocalSettingsJson(): string {
  const settings = {
    permissions: {
      allow: ['Read', 'Glob', 'Grep', 'Edit', 'Write', 'Bash'],
    },
    hooks: {
      PreToolUse: [
        {
          matcher: 'Bash',
          hooks: [
            {
              type: 'command',
              command: '.claude/hooks/classify-bash.sh',
            },
          ],
        },
      ],
    },
  };
  return JSON.stringify(settings, null, 2) + '\n';
}

const LOCAL_BACKUP_SUFFIX = '.backup';

/**
 * Backup user's settings.local.json before a Work run, so our permissions take effect.
 * Idempotent: only backs up if the file exists AND no backup already present.
 */
export function backupLocalSettings(projectPath: string): void {
  const localSettings = path.join(projectPath, '.claude', 'settings.local.json');
  const backupFile = localSettings + LOCAL_BACKUP_SUFFIX;

  if (!fs.existsSync(localSettings)) return; // nothing to back up
  if (fs.existsSync(backupFile)) return;      // already backed up (e.g. another active Work)

  fs.copyFileSync(localSettings, backupFile);
}

/**
 * Restore user's settings.local.json after a Work run completes.
 * If no backup exists, removes our settings (user had no local settings before the run).
 */
export function restoreLocalSettings(projectPath: string): void {
  const localSettings = path.join(projectPath, '.claude', 'settings.local.json');
  const backupFile = localSettings + LOCAL_BACKUP_SUFFIX;

  if (fs.existsSync(backupFile)) {
    fs.copyFileSync(backupFile, localSettings);
    fs.unlinkSync(backupFile);
  }
  // No backup = user had no settings.local.json before the run.
  // Leave our file in place — it's harmless and ensures permissions until next sync.
}

/**
 * Write our permissions to settings.local.json for the duration of a Work run.
 */
export function writeLocalSettings(projectPath: string): void {
  const claudeDir = path.join(projectPath, '.claude');
  if (!fs.existsSync(claudeDir)) {
    fs.mkdirSync(claudeDir, { recursive: true });
  }
  const localSettings = path.join(claudeDir, 'settings.local.json');
  fs.writeFileSync(localSettings, generateLocalSettingsJson(), 'utf-8');
}

export { generateHookScript };
